/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CopilotoRouteImport } from './routes/copiloto'
import { Route as IndicacaoRouteImport } from './routes/indicacao'
import { Route as Latbus2026RouteImport } from './routes/latbus-2026'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as SeloVerdeRouteImport } from './routes/selo-verde'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiSeloRouteImport } from './routes/api/selo'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProdutosSsEvolutionRouteImport } from './routes/produtos.ss-evolution'
import { Route as ProdutosSsPerformanceRouteImport } from './routes/produtos.ss-performance'
import { Route as ProdutosSsStartRouteImport } from './routes/produtos.ss-start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotoRoute = CopilotoRouteImport.update({
  id: '/copiloto',
  path: '/copiloto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicacaoRoute = IndicacaoRouteImport.update({
  id: '/indicacao',
  path: '/indicacao',
  getParentRoute: () => rootRouteImport,
} as any)
const Latbus2026Route = Latbus2026RouteImport.update({
  id: '/latbus-2026',
  path: '/latbus-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeloVerdeRoute = SeloVerdeRouteImport.update({
  id: '/selo-verde',
  path: '/selo-verde',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeloRoute = ApiSeloRouteImport.update({
  id: '/api/selo',
  path: '/api/selo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSsEvolutionRoute = ProdutosSsEvolutionRouteImport.update({
  id: '/produtos/ss-evolution',
  path: '/produtos/ss-evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSsPerformanceRoute = ProdutosSsPerformanceRouteImport.update({
  id: '/produtos/ss-performance',
  path: '/produtos/ss-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosSsStartRoute = ProdutosSsStartRouteImport.update({
  id: '/produtos/ss-start',
  path: '/produtos/ss-start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/copiloto': typeof CopilotoRoute
  '/indicacao': typeof IndicacaoRoute
  '/latbus-2026': typeof Latbus2026Route
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/selo-verde': typeof SeloVerdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/selo': typeof ApiSeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/ss-evolution': typeof ProdutosSsEvolutionRoute
  '/produtos/ss-performance': typeof ProdutosSsPerformanceRoute
  '/produtos/ss-start': typeof ProdutosSsStartRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/copiloto': typeof CopilotoRoute
  '/indicacao': typeof IndicacaoRoute
  '/latbus-2026': typeof Latbus2026Route
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/selo-verde': typeof SeloVerdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/selo': typeof ApiSeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/ss-evolution': typeof ProdutosSsEvolutionRoute
  '/produtos/ss-performance': typeof ProdutosSsPerformanceRoute
  '/produtos/ss-start': typeof ProdutosSsStartRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/copiloto': typeof CopilotoRoute
  '/indicacao': typeof IndicacaoRoute
  '/latbus-2026': typeof Latbus2026Route
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/selo-verde': typeof SeloVerdeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/selo': typeof ApiSeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/produtos/ss-evolution': typeof ProdutosSsEvolutionRoute
  '/produtos/ss-performance': typeof ProdutosSsPerformanceRoute
  '/produtos/ss-start': typeof ProdutosSsStartRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/copiloto'
    | '/indicacao'
    | '/latbus-2026'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/selo-verde'
    | '/sitemap.xml'
    | '/api/leads'
    | '/api/selo'
    | '/blog/$slug'
    | '/produtos/ss-evolution'
    | '/produtos/ss-performance'
    | '/produtos/ss-start'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/copiloto'
    | '/indicacao'
    | '/latbus-2026'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/selo-verde'
    | '/sitemap.xml'
    | '/api/leads'
    | '/api/selo'
    | '/blog/$slug'
    | '/produtos/ss-evolution'
    | '/produtos/ss-performance'
    | '/produtos/ss-start'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/copiloto'
    | '/indicacao'
    | '/latbus-2026'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/selo-verde'
    | '/sitemap.xml'
    | '/api/leads'
    | '/api/selo'
    | '/blog/$slug'
    | '/produtos/ss-evolution'
    | '/produtos/ss-performance'
    | '/produtos/ss-start'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  CopilotoRoute: typeof CopilotoRoute
  IndicacaoRoute: typeof IndicacaoRoute
  Latbus2026Route: typeof Latbus2026Route
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  SeloVerdeRoute: typeof SeloVerdeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiSeloRoute: typeof ApiSeloRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProdutosSsEvolutionRoute: typeof ProdutosSsEvolutionRoute
  ProdutosSsPerformanceRoute: typeof ProdutosSsPerformanceRoute
  ProdutosSsStartRoute: typeof ProdutosSsStartRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copiloto': {
      id: '/copiloto'
      path: '/copiloto'
      fullPath: '/copiloto'
      preLoaderRoute: typeof CopilotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicacao': {
      id: '/indicacao'
      path: '/indicacao'
      fullPath: '/indicacao'
      preLoaderRoute: typeof IndicacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latbus-2026': {
      id: '/latbus-2026'
      path: '/latbus-2026'
      fullPath: '/latbus-2026'
      preLoaderRoute: typeof Latbus2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selo-verde': {
      id: '/selo-verde'
      path: '/selo-verde'
      fullPath: '/selo-verde'
      preLoaderRoute: typeof SeloVerdeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selo': {
      id: '/api/selo'
      path: '/api/selo'
      fullPath: '/api/selo'
      preLoaderRoute: typeof ApiSeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/ss-evolution': {
      id: '/produtos/ss-evolution'
      path: '/produtos/ss-evolution'
      fullPath: '/produtos/ss-evolution'
      preLoaderRoute: typeof ProdutosSsEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/ss-performance': {
      id: '/produtos/ss-performance'
      path: '/produtos/ss-performance'
      fullPath: '/produtos/ss-performance'
      preLoaderRoute: typeof ProdutosSsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/ss-start': {
      id: '/produtos/ss-start'
      path: '/produtos/ss-start'
      fullPath: '/produtos/ss-start'
      preLoaderRoute: typeof ProdutosSsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  CopilotoRoute: CopilotoRoute,
  IndicacaoRoute: IndicacaoRoute,
  Latbus2026Route: Latbus2026Route,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  SeloVerdeRoute: SeloVerdeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiSeloRoute: ApiSeloRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProdutosSsEvolutionRoute: ProdutosSsEvolutionRoute,
  ProdutosSsPerformanceRoute: ProdutosSsPerformanceRoute,
  ProdutosSsStartRoute: ProdutosSsStartRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
